name: release package

on:
  push:
    branches:
      - main
    paths:
      - "frame/manifest.json"

permissions: write-all

jobs:
  sync:
    uses: deepakdinesh1123/workflow-test/.github/workflows/release-package.yml@main
    with:
      manifest-file-path: "frame/manifest.json"
      aws-pkg-name: "frame"
    secrets: inherit